export const ICONPREFIX = '/static/app/img/file-icon/';

export const _DATA = {
    tableData: [],
    colData: [],
    colCfg: {
        def: "",
        column: [],
    },
    actions: [],
    staData: [],
    pubCfg: {
        isPublic: false,
        attach: "",
        name: "",
        subBtnText: "",
        doneText: "",
        qrList: [],
        rules: [],
        submitable: true,
        formLabelPosition: "top",
        formLabelWith: "",
    },
    upload: {
        is_wf: "0",
        wf_code: "",
        mainfields: [],
        relate_table: "0",
        relate_type: "0",
        relate_unique: "",
        childTable: []
    },
    rules: [],
    subCfg: [],
    stageData: [],
    asstable: [],
    inner_api: {
        inner_type: "",
        async_type: "",
        async_stime: "",
        async_etime: "",
        inner_return: [],
        inner_params: {},
        field_config: {},
        api_tag: "",
        return_tag: "",
        incre_type: "",
        incre_field: "",
    },
    outer_api: {},
};