export const FIELDS = [
    { field: "pro_name", display: "项目", width: "240", title: true },
    { field: "pro_code", display: "项目编号", width: "140" },
    { field: "d_tag_x", display: "类型", width: "120" },
    { field: "wt_unit", display: "委托单位", width: "120" },
    { field: "js_unit", display: "建设单位", width: "120" },
    { field: "xs_user_x", display: "销售人员", width: "90" },
    { field: "xs_dept_x", display: "销售部门", width: "90" },
    { field: "xm_user_x", display: "项目组长", width: "90" },
    { field: "sd_user_x", display: "编制主持人", width: "90" },
    { field: "bz_user_x", display: "编制人员", width: "90" },
    { field: "bz_dept_x", display: "编制部门", width: "90" },
    { field: "is_qc_x", display: "是否期初", width: "80" },
    { field: "is_gd_x", display: "是否归档", width: "80" },
    { field: "is_sh_x", display: "是否审核", width: "80" },
];